version: 0.2

phases:
  pre_build:
    commands:
      - echo "Checking identity..."
      - aws sts get-caller-identity
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo "Build started on `date`"
      - IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "Building Docker image..."
      - docker build -t $IMAGE_URI .
      - echo "Pushing Docker image..."
      - docker push $IMAGE_URI

  post_build:
    commands:
      - echo "Creating imagedefinitions.json for CodeDeploy..."
      - printf '[{"name":"%s","imageUri":"%s"}]' $ECR_REPO $IMAGE_URI > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml
    - scripts/**
