version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Building Docker image...
      - docker build -t $IMAGE_URI .
      - echo Pushing Docker image...
      - docker push $IMAGE_URI
  post_build:
    commands:
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $ECR_REPO $IMAGE_URI > imageDetail.json

      # 👇 Replace PLACEHOLDER_IMAGE with the actual ECR image URI
      - echo Updating Kubernetes manifests...
      - sed -i "s|PLACEHOLDER_IMAGE|$IMAGE_URI|g" k8s/deployment.yml

      # 👇 Apply manifests to EKS
      - echo Applying manifests to EKS...
      - kubectl apply -f k8s/deployment.yml -f k8s/service.yml

artifacts:
  files:
    - imageDetail.json
