apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app   # 👈 added here for consisten
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: PLACEHOLDER_IMAGE   # 👈 will be replaced in pipeline
        ports:
        - containerPort: 3000
